//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunSatis_EntityUygulama_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UrunSatisEntities : DbContext
    {
        public UrunSatisEntities()
            : base("name=UrunSatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLKATEGORI> TBLKATEGORI { get; set; }
        public virtual DbSet<TBLMUSTERI> TBLMUSTERI { get; set; }
        public virtual DbSet<TBLSATIS> TBLSATIS { get; set; }
        public virtual DbSet<TBLURUN> TBLURUN { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
    
        public virtual ObjectResult<MARKAGETIR_Result> MARKAGETIR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MARKAGETIR_Result>("MARKAGETIR");
        }
    
        public virtual ObjectResult<string> MAKSMARKA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MAKSMARKA");
        }
    }
}
